# Generated by Django 5.1.2 on 2024-10-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('CV', 'Colisão entre Veículos'), ('AP', 'Atropelamento de Pedestre'), ('OT', 'Outro')], default='OT', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
